import './globals.css'

export const metadata = {
  title: 'Grand',
  icons : {
    icon : "/icon.svg",
    type : "image/svg"
  },
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
